### ISSUE TITLE
But has anyone done a debug tools image that they keep up to date?

### ISSUE THREAD

**Issue by mjaggard** [hmarr/debug-tools#1]
Why even bother publishing this if you're not planning on keeping it up to date?

**Comment by hmarr** [comment]
I recommend giving the GitHub [code of conduct](https://docs.github.com/en/site-policy/github-terms/github-community-code-of-conduct) a read. Rudeness won't get you very far, please try to be constructive and courteous in the future.

**Comment by mjaggard** [comment]
Apologies, it wasn't intended to be rude but I was frustrated.

**Comment by hmarr** [comment]
Apology accepted. If there are specific things inside the image you'd like to be updated, let me know.
